# generated by datamodel-codegen:
#   filename:  api.yml
#   timestamp: 2025-10-21T11:54:26+00:00

from __future__ import annotations

from typing import List, Optional
from uuid import UUID
from datetime import datetime

from pydantic import BaseModel


class UserDTO(BaseModel):
    id: Optional[UUID] = None
    name: Optional[str] = None
    email: Optional[str] = None
    contacts: Optional[List[str]] = None


class PictureDTO(BaseModel):
    id: Optional[UUID] = None
    path: Optional[str] = None
    analyse_by: Optional[str] = None
    pourcentage: Optional[float] = None
    date_detection: Optional[datetime] = None
    date_validation: Optional[datetime] = None
