from typing import Protocol, Collection
from app.room.domain.entity.room import Room


class RoomCatalog(Protocol):
    def find_all(self) -> Collection[Room]: ...
    def save(self, room: Room) -> None: ...
    def find_by_name(self, name: str) -> Room: ...
    def find_by_id(self, room_id: str) -> Room: ...
    def delete(self, room_id: str) -> None: ...
    def low_picture_coverage_rooms(self) -> Collection[Room]: ...
    def total_rooms_count(self) -> int: ...
    def find_all_validated(self) -> Collection[Room]: ...
