"""Initial schema

Revision ID: 198468c4ad55
Revises:
Create Date: 2025-12-03 10:01:36.355790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "198468c4ad55"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("input_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
        sa.UniqueConstraint("model_id"),
    )
    op.create_table(
        "pictures",
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("analyzed_by", sa.String(length=255), nullable=True),
        sa.Column("recognition_percentage", sa.Float(), nullable=True),
        sa.Column(
            "analyse_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "validation_date", sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("image_id"),
        sa.UniqueConstraint("image_id"),
    )
    op.create_table(
        "roles",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("role_id"),
    )
    op.create_table(
        "rooms",
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("departement", sa.String(length=100), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("room_id"),
        sa.UniqueConstraint("room_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("rooms")
    op.drop_table("roles")
    op.drop_table("pictures")
    op.drop_table("models")
    # ### end Alembic commands ###
