from typing import Protocol, Collection, Union
from uuid import UUID
from app.picture.domain.entity.picture import Picture


class PictureCatalog(Protocol):
    def find_all(self) -> Collection[Picture]: ...
    def save(self, picture: Picture) -> None: ...
    def update(self, picture_id: Union[str, UUID], updates: dict): ...
    def find_by_id(self, picture_id: Union[str, UUID]) -> Picture: ...
    def find_by_not_validated(self) -> Collection[Picture]: ...
    def delete(self, picture_id: Union[str, UUID]) -> None: ...
