from typing import Protocol, Collection, Optional
from uuid import UUID

from app.user.domain.entity.user import User


class UserCatalog(Protocol):
    def find_all(self) -> Collection[User]: ...
    def save(self, user: User) -> None: ...
    def find_by_email(self, email: str) -> Optional[User]: ...
    def find_by_id(self, user_id: UUID) -> Optional[User]: ...
