from typing import Protocol, Collection
from app.model.domain.entity.model import Model


class ModelCatalog(Protocol):
    def find_all(self) -> Collection[Model]: ...
    def find_by_id(self, model_id: str) -> Model | None: ...
    def save(self, model: Model) -> Model: ...
    def find_active_model(self) -> Model | None: ...
