FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG EXPO_PUBLIC_BACKEND_API_ADDRESS
# Make the EXPO_PUBLIC_BACKEND_API_ADDRESS available during the build
ENV EXPO_PUBLIC_BACKEND_API_ADDRESS=${EXPO_PUBLIC_BACKEND_API_ADDRESS}

RUN npx expo export --platform web

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
