openapi: 3.0.3
info:
  title: SAE5 API
  version: 1.0.0

paths:
  /users:
    $ref: './users/users.yml'
  /pictures:
    $ref: './pictures/pictures.yml'
  /rooms:
    $ref: './rooms/rooms.yml'

components:
  schemas:
    UserDTO:
      $ref: './users/DTO/userDTO.yml'
    PictureDTO:
      $ref: './pictures/DTO/pictureDTO.yml'
    RoomDTO:
      $ref: './rooms/DTO/roomDTO.yml'
